#服务器配置
server:
  port: 80
  servlet:
    context-path: /rentalRoom
    session:
      timeout: 30m

#spring配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  devtools:
    restart:
      enabled: true
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/rentalroom?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

#mybatis配置
mybatis:
  type-aliases-package: com.gxust.edu.rental_room.domain,com.gxust.edu.rental_room.query
  mapper-locations: classpath:/mapper/*Mapper.xml

#分页插件
pagehelper:
  helperDialect: mysql
  offset-as-page-num: true
  row-bounds-with-count: true
  page-size-zero: true
  reasonable: true
  supportMethodsArguments: true
  params: pageNum=start;pageSize=limit;
  returnPageInfo: check
logging:
  level:
    com.gxust.edu.rental_room.mapper: debug